const AUTH_USER_SET_PROFILE = 'AUTH_USER_SET_PROFILE';
const AUTH_USER_UNSET_PROFILE = 'AUTH_USER_UNSET_PROFILE';
const RECEIVE_FETCH_LOGOUT_ERROR = 'RECEIVE_FETCH_LOGOUT_ERROR';
const RECEIVE_FETCH_LOGOUT_SUCCESS = 'RECEIVE_FETCH_LOGOUT_SUCCESS';
const RECEIVE_LOGIN_SUCCESS = 'RECEIVE_LOGIN_SUCCESS';
const RECEIVE_LOGOUT_ERROR = 'RECEIVE_LOGOUT_ERROR';
const RECEIVE_LOGOUT_SUCCESS = 'RECEIVE_LOGOUT_SUCCESS';
const RECEIVE_TWITTER_AUTHORIZE_ERROR = 'RECEIVE_TWITTER_AUTHORIZE_ERROR';
const RECEIVE_TWITTER_AUTHORIZE_SUCCESS = 'RECEIVE_TWITTER_AUTHORIZE_SUCCESS';
const REQUEST_LOGIN = 'REQUEST_LOGIN';
const REQUEST_LOGOUT = 'REQUEST_LOGOUT';
const REQUEST_TWITTER_AUTHORIZE = 'REQUEST_TWITTER_AUTHORIZE';

export default {
  AUTH_USER_SET_PROFILE,
  AUTH_USER_UNSET_PROFILE,
  RECEIVE_FETCH_LOGOUT_ERROR,
  RECEIVE_FETCH_LOGOUT_SUCCESS,
  RECEIVE_LOGIN_SUCCESS,
  RECEIVE_LOGOUT_ERROR,
  RECEIVE_LOGOUT_SUCCESS,
  RECEIVE_TWITTER_AUTHORIZE_ERROR,
  RECEIVE_TWITTER_AUTHORIZE_SUCCESS,
  REQUEST_LOGIN,
  REQUEST_LOGOUT,
  REQUEST_TWITTER_AUTHORIZE,
};
